import { getAuth, signOut } from "firebase/auth"
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from "next/router"
import useFirebaseUser from "../hooks/useUser"

const Home: NextPage = () =>
{
    const router = useRouter();
    const user = useFirebaseUser();

    const login = async () =>
    {
        await router.push( "/auth/login" )
    }

    const logout = async () =>
    {
        await signOut( getAuth() );
    }

    return (
        <div>
            <Head>
                <title>Create Next App Peperino</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <>
            </>
        </div>
    )
}

export default Home
