import { getAuth, signOut } from "firebase/auth"
import type { NextPage } from 'next'
import Head from 'next/head'
import { useRouter } from "next/router"
import AuthCheck from "../components/AuthCheck"
import useFirebaseUser from "../hooks/useFirebaseUser"
import styles from '../styles/Home.module.css'

const Home: NextPage = () =>
{
    const router = useRouter();
    const user = useFirebaseUser();

    const login = async () =>
    {
        await router.push( "/auth/login" )
    }

    const logout = async () =>
    {
        await signOut( getAuth() );
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App Peperino</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p>{`Hello ${user?.email ?? ""}, im peperino`}</p>

                <AuthCheck fallback={
                    <button onClick={login}>Einloggen</button>
                }>
                    <button onClick={logout}>Ausloggen</button>
                </AuthCheck>
            </main>
        </div>
    )
}

export default Home
