import type { NextPage } from 'next'
import Head from 'next/head'
import Link from "next/link"
import AuthCheck from "../components/AuthCheck"
import styles from '../styles/Home.module.css'

const Home: NextPage = () =>
{
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App Peperino</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p>{"Hello, im peperino"}</p>

                <Link href={"/login"}>
                    <button>
                        <AuthCheck fallback={<>Einloggen</>}>
                            <>Ausloggen</>
                        </AuthCheck>
                    </button>
                </Link>
            </main>
        </div>
    )
}

export default Home
